---
apiVersion: v1
kind: Namespace
metadata:
  name: kured
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kured-helm-repository
  namespace: kured
spec:
  interval: 5m0s
  url: https://kubereboot.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  install:
    remediation:
      retries: 3
  interval: 5m
  chart:
    spec:
      chart: kured
      version: ^5.10.0
      sourceRef:
        kind: HelmRepository
        name: kured-helm-repository
      interval: 1m
  values:
    configuration:
      rebootCommand: /usr/bin/systemctl reboot
