---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  install:
    remediation:
      retries: 3
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: ^2.34.0
      sourceRef:
        kind: HelmRepository
        name: pihole-helm-repository
      interval: 1m
  values:
    serviceDhcp:
      enabled: false
    ingress:
      enabled: false
    virtualHost: "pihole.l8s.linnaeus.dev"
    serviceDns:
      type: LoadBalancer
      loadBalancerClass: io.cilium/l2-announcer
      loadBalancerIP: 10.0.1.201
      annotations:
        "lbipam.cilium.io/sharing-key": "1234" # shared IP needed for udp/tcp
    admin:
      existingSecret: pihole-admin-secret
