---
apiVersion: v1
kind: Namespace
metadata:
  name: reflector
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: reflector-helm-repository
  namespace: reflector
spec:
  interval: 5m0s
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  install:
    remediation:
      retries: 3
  interval: 5m
  chart:
    spec:
      chart: reflector
      version: ^9.1.34
      sourceRef:
        kind: HelmRepository
        name: reflector-helm-repository

    