---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-s3
  namespace: seaweedfs
spec:
  defaultBackend:
    service:
      name: seaweedfs-filer
      port:
        number: 8333
  ingressClassName: tailscale
  tls:
    - hosts:
        - seaweedfs-s3
