---
apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  # Use latest stable SeaweedFS image
  image: chrislusf/seaweedfs:latest
  volumeServerDiskCount: 1

  # Master servers - 3 replicas on control plane nodes
  master:
    replicas: 3
    # 1GB volumes for flexibility with many buckets
    volumeSizeLimitMB: 1024
    # Default replication: 010 = 1 replica on different rack (node)
    defaultReplication: "010"

    # Pin masters to control plane nodes
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  # Volume servers - Use topology to spread across 3 worker nodes
  # Set replicas to 0 to disable simple volume group
  volume:
    replicas: 0

    # Default settings inherited by all topology groups
    requests:
      storage: 200Gi
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

    # Use local-path-provisioner for direct NVMe access
    storageClassName: "local-path"

  # Topology-aware volume server deployment across 3 RPi5 workers
  volumeTopology:
    worker-1:
      replicas: 1
      rack: "rack1"
      dataCenter: "dc1"
      nodeSelector:
        kubernetes.io/hostname: worker-x1y2
      requests:
        storage: 200Gi

    worker-2:
      replicas: 1
      rack: "rack2"
      dataCenter: "dc1"
      nodeSelector:
        kubernetes.io/hostname: worker-z5w9
      requests:
        storage: 200Gi

    worker-3:
      replicas: 1
      rack: "rack3"
      dataCenter: "dc1"
      nodeSelector:
        kubernetes.io/hostname: worker-m3n7
      requests:
        storage: 200Gi

  # Filer servers - 2 replicas with S3 and embedded IAM
  filer:
    replicas: 2

    # Enable S3 API with embedded IAM and credential config
    s3:
      enabled: true
      configSecret:
        name: seaweedfs-s3-config
        key: seaweedfs_s3_config.json
    iam: true  # Embedded IAM for S3 authentication

    # Filer metadata storage configuration (leveldb2 for single filer)
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"

      # Configure S3 bucket path
      [filer.options]
      buckets_folder = "/buckets"

    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "1Gi"

    service:
      type: ClusterIP

  # IAM port configuration for embedded IAM
  iam:
    port: 8111
