---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale-helm-repository
  namespace: tailscale
spec:
  interval: 5m0s
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  install:
    remediation:
      retries: 3
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.90.9
      sourceRef:
        kind: HelmRepository
        name: tailscale-helm-repository
      interval: 1m
