---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-exporter
  namespace: pihole
  labels:
    app: pihole-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole-exporter
  template:
    metadata:
      labels:
        app: pihole-exporter
    spec:
      containers:
        - name: pihole-exporter
          image: ekofr/pihole-exporter:latest
          ports:
            - name: metrics
              containerPort: 9617
              protocol: TCP
          env:
            - name: PIHOLE_PROTOCOL
              value: "http"
            - name: PIHOLE_HOSTNAME
              value: "pihole-web.pihole.svc.cluster.local"
            - name: PIHOLE_PORT
              value: "80"
            - name: PIHOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-admin-secret
                  key: password
            - name: PORT
              value: "9617"
            - name: INTERVAL
              value: "30s"
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
