---
apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: pihole
  labels:
    app: pihole-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9617
      targetPort: metrics
      protocol: TCP
  selector:
    app: pihole-exporter
