---
apiVersion: v1
kind: Namespace
metadata:
  name: seaweedfs-operator
---
# ServiceAccount needed by webhook certificate jobs even when webhooks are disabled
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seaweedfs-operator-update-webhook-certificates
  namespace: seaweedfs-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: seaweedfs-operator-update-webhook-certificates
  namespace: seaweedfs-operator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seaweedfs-operator-update-webhook-certificates
  namespace: seaweedfs-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seaweedfs-operator-update-webhook-certificates
subjects:
  - kind: ServiceAccount
    name: seaweedfs-operator-update-webhook-certificates
    namespace: seaweedfs-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seaweedfs-operator-update-webhook-certificates
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: seaweedfs-operator-update-webhook-certificates
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seaweedfs-operator-update-webhook-certificates
subjects:
  - kind: ServiceAccount
    name: seaweedfs-operator-update-webhook-certificates
    namespace: seaweedfs-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seaweedfs-operator
  namespace: seaweedfs-operator
spec:
  interval: 1h
  url: https://seaweedfs.github.io/seaweedfs-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs-operator
  namespace: seaweedfs-operator
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: seaweedfs-operator
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-operator
        namespace: seaweedfs-operator
      interval: 1h
  values:
    # Webhook must be disabled initially due to certificate generation issue
    # Enable after first successful deployment
    webhook:
      enabled: false

    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 50Mi

    # Enable ServiceMonitor for Prometheus if available
    serviceMonitor:
      enabled: false

    # Enable Grafana dashboard
    grafanaDashboard:
      enabled: true
