---
apiVersion: v1
kind: Namespace
metadata:
  name: seaweedfs-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seaweedfs-operator
  namespace: seaweedfs-operator
spec:
  interval: 1h
  url: https://seaweedfs.github.io/seaweedfs-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs-operator
  namespace: seaweedfs-operator
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: seaweedfs-operator
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-operator
        namespace: seaweedfs-operator
      interval: 1h
  values:
    # Webhook must be disabled initially due to certificate generation issue
    # Enable after first successful deployment
    webhook:
      enabled: false

    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 50Mi

    # Enable ServiceMonitor for Prometheus if available
    serviceMonitor:
      enabled: false

    # Enable Grafana dashboard
    grafanaDashboard:
      enabled: true
