---
apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vaultwarden-helm-repository
  namespace: vaultwarden
spec:
  interval: 1m
  url: https://github.com/guerzon/vaultwarden
  ref:
    semver: ^0.34.3
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  install:
    remediation:
      retries: 3
  interval: 5m
  chart:
    spec:
      chart: ./charts/vaultwarden
      sourceRef:
        kind: GitRepository
        name: vaultwarden-helm-repository
      interval: 1m
  values:
    adminToken:
      existingSecret: vault-admin-secret
      existingSecretKey: ADMIN_TOKEN
    signupsAllowed: true
    signupDomains: null
    ingress:
      enabled: false
    smtp:
      host: null
    data:
      name: "vaultwarden-data"
      size: "1Gi"
