---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx-helm-repository
  namespace: ingress-nginx
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ingress-nginx
      version: ^4.13.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-helm-repository
      interval: 1m
  values:
    controller:
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          lbipam.cilium.io/ips: "10.0.1.200"
