---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  install:
    remediation:
      retries: 3
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: ^8.4.1
      sourceRef:
        kind: HelmRepository
        name: nextcloud-helm-repository
      interval: 1m
  values:
    ingress:
      enabled: true
      className: tailscale
    tls:
      - hosts:
          - nextcloud
    nextcloud:
      host: nextcloud.taile77d89.ts.net
      existingSecret:
        enabled: true
        secretName: nextcloud-admin-secret
        usernameKey: username
        passwordKey: password
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: mysql
      host: nextcloud-mariadb
      user: nextcloud
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-mariadb-secret-root
        passwordKey: mariadb-password
    mariadb:
      enabled: true
      auth:
        database: nextcloud
        username: nextcloud
        existingSecret: nextcloud-mariadb-secret-root
      primary:
        persistence:
          enabled: true
          storageClass: "longhorn"
    persistence:
      enabled: true
      storageClass: "longhorn"
      size: 200Gi
