---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  install:
    remediation:
      retries: 3
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: ^9.2.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud-helm-repository
      interval: 1m
  values:
    ingress:
      enabled: false
    phpClientHttpsFix:
      enabled: true
      protocol: https
    nextcloud:
      trustedDomains:
        - nextcloud.taile77d89.ts.net
      # configs:
      #   custom.config.php: |
      #     <?php
      #     $CONFIG = array (
      #       'overwrite.cli.url' => 'https://nextcloud.taile77d89.ts.net',
      #       'overwriteprotocol' => 'https',
      #     );
      host: nextcloud.taile77d89.ts.net
      existingSecret:
        enabled: true
        secretName: nextcloud-admin-secret
        usernameKey: username
        passwordKey: password
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: mysql
      host: nextcloud-mariadb
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-mariadb-secret-root
        passwordKey: mariadb-password
        usernameKey: mariadb-user
    persistence:
      enabled: true
      hostPath: /mnt/nextcloud
    nodeSelector:
      kubernetes.io/hostname: worker-m3n7
    mariadb:
      enabled: true
      auth:
        database: nextcloud
        username: nextcloud
        existingSecret: nextcloud-mariadb-secret-root
      primary:
        persistence:
          enabled: true
          storageClass: "longhorn"
